version: '3.7'

services:
  undetected-chromedriver:
    image: ultrafunk/undetected-chromedriver
    ports:
      - "443:3306"
    volumes:
      - ./app/src/:app/src/
      - ./driver/:driver/
    configs:
      - my_config
    command:
      - ipython app/main.py

configs:
  my_config:
    file: ./config.ini
  my_log: 
    file: ./mylog.log
  my_users: 
    file: ./users.ini  
  